import { createRoot } from "react-dom/client";
import App from "./App";
import "./index.css";
import { registerSW } from "virtual:pwa-register";

window.addEventListener("unhandledrejection", (e) => {
  console.warn("Unhandled rejection:", e.reason);
  e.preventDefault();
});

createRoot(document.getElementById("root")!).render(<App />);

// Auto-updating service worker (generated by vite-plugin-pwa / Workbox)
registerSW({ onNeedRefresh() {}, onOfflineReady() {} });
